//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empolee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Depertmant { get; set; }
    
        public virtual TDepertmant TDepertmant { get; set; }
    }
}
