//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int FeatureID { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureDes { get; set; }
        public string FeatureImageUrl { get; set; }
    }
}
