//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref
    {
        public int IDRef { get; set; }
        public string RefNameSurname { get; set; }
        public string RefMail { get; set; }
        public string RefNumber { get; set; }
        public string RefJob { get; set; }
        public string ImageUrl { get; set; }
    }
}
